version: 2 
updates:
  # ðŸ”„ Keep GitHub Actions dependencies  Chnages
  - package-ecosystem: "github-actions"
    directory: "/"  # Location of workflow file
    schedule:
      interval: "weekly"  # Options: "daily", "weekly", 
    open-pull-requests-limit: 10
    commit-message:
      prefix: "actions"
